language: generic

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal/packages
  - $HOME/.cabal/store
  - $HOME/.stack

matrix:
  include:
  - env: STACKAGEVER=lts-13.14

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- docker pull fpco/stack-build:$STACKAGEVER
- stack --version
- stack --docker --no-terminal test --install-ghc --only-dependencies --docker-auto-pull

script:
- stack --docker --no-terminal test --haddock --no-haddock-deps
- stack --docker --no-terminal image container
