# This is the complex Travis configuration, which is intended for use
# on open source libraries which need compatibility across multiple GHC
# versions, must work with cabal-install, and should be
# cross-platform. For more information and other options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/.stack-work

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC
- export PATH=${HOME}/.local/bin:${PATH}
- mkdir -p ${HOME}/.local/bin
- |
  set -ex
  case "$TRAVIS_OS_NAME" in
    linux)
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      ;;
    osx)
      brew install z3
      travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
      ;;
  esac
  set +ex

install:
- stack --version
- docker pull fpco/stack-build:lts-13.9

script:
- stack --no-terminal test
- stack --docker image container
