name: basic-examples

default-extensions: 
- OverloadedStrings

dependencies:
- base

library:
  source-dirs:           src

executables:
  basic-examples:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ld-options:
    - -static
    dependencies:
    - basic-examples

tests:
  examples-spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ld-options:
    - -static
    dependencies:
    - basic-examples
    - hspec
    - QuickCheck
    - smallcheck
    - hlint
  examples-doc:
    main:                doc.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ld-options:
    - -static
    dependencies:
    - basic-examples
    - doctest
    other-modules: []
